name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws --endpoint-url https://s3.routing.cafe s3 cp src/ s3://routing.cafe --recursive
